### ISSUE TITLE
Publish Keygate SDK to cargo

### ISSUE THREAD

**Issue by vincentes** [keygate-vault/sdk#1]
**Description**
* A public API to interface internal Keygate SDK methods and structs should be defined.
* Change project structure to be based on a `lib.rs` file not a `main.rs` executable.
* The Keygate SDK should be published to Cargo: developers should be able to pull the Keygate SDK to their Cargo.toml.

**Comment by QuinoBallara** [comment]
-  Public methods and structs defined. 
- Added docs to structs and methods.
-  Added a new method `create_wallet_write_file()` to generate a file with the _wallet_id_ when creating a new wallet.

[Link to Branch](https://github.com/keygate-vault/sdk/tree/feature/cargo-publish)

**Comment by vincentes** [comment]
Can you add the missing sections to the README.md?
