### ISSUE TITLE
Use Case: CLI integration

### ISSUE THREAD

**Issue by vincentes** [keygate-vault/sdk#2]
**Description**
Create a CLI that allows a user to:
* Create a wallet
* Check their balance
* Send a basic transaction using that wallet

Two options:
* Interactive CLI
* CLI via commands `keygate balance`, `keygate transact`, `keygate init` (to setup wallet).

Created wallet principal id should be persisted.

**Comment by QuinoBallara** [comment]
Done

[Link to Branch](https://github.com/keygate-vault/sdk/tree/feature/cli)
